name: Update Weather Locations Plot

on:
  schedule:
    - cron: '0 0-21/3 * * *'
  workflow_dispatch:

jobs:
  update_plot:
    name: Update plot with new location weather data
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Setup Python
        uses: actions/setup-python@v2
        with:
          python-version: '3.7'
          cache: 'pip'

      - name: Install Dependencies
        run: pip install -r articles/github-actions/requirements.txt

      - name: Run Script and Update Plot
        run: |
          cd articles/github-actions/
          jupyter nbconvert --to script weather_locations.ipynb
          python weather_locations.py
      
      - name: Commit and Push Changes
        run: |
          git config --local user.email "actions@github.com"
          git config --local user.name "GitHub Actions"
	  git add articles/github-actions/weather_locations.csv 
	  git add articles/github-actions/weather_locations.png
          git commit -m "Updated plot on `date` with GitHub Actions" || echo "No Changes to Commit"
          git push origin master || echo "No Changes to Commit"
